welcome_message: "Добро пожаловать в JAR Tool!"
open_file_button: "Открыть JAR файл"
decompile_button: "Декомпилировать"
compile_button: "Компилировать в JAR"
settings_button: "Настройки"
select_file_prompt: "Выберите JAR файл"
file_selected: "Вы выбрали: {}"
progress_message: "Обработка..."
decompile_complete: "Декомпиляция завершена!"
error_title: "Ошибка"
error_message: "Произошла ошибка: {}"
compilation_success: "Компиляция успешна!"
compilation_failure: "Ошибка компиляции!"
jar_creation_success: "JAR файл успешно создан!"
jar_creation_failure: "Не удалось создать JAR файл!"