welcome_message: "Welcome to JAR Tool!"
open_file_button: "Open JAR File"
decompile_button: "Decompile"
compile_button: "Compile to JAR"
settings_button: "Settings"
select_file_prompt: "Select a JAR file"
file_selected: "You selected: {}"
progress_message: "Processing..."
decompile_complete: "Decompilation complete!"
error_title: "Error"
error_message: "Error occurred: {}"
compilation_success: "Compilation successful!"
compilation_failure: "Compilation failed!"
jar_creation_success: "JAR file created successfully!"
jar_creation_failure: "Failed to create JAR file!"