#░░█ ▄▀█ █▀█ ▀█▀ █▀█ █▀█ █░░
#█▄█ █▀█ █▀▄ ░█░ █▄█ █▄█ █▄▄
#
#╔═══╗─────╔═╗
#║╔═╗║─────║╔╝
#║║─╚╬══╦═╦╝╚╦╦══╗
#║║─╔╣╔╗║╔╬╗╔╬╣╔╗║
#║╚═╝║╚╝║║║║║║║╚╝║
#╚═══╩══╩╝╚╩╝╚╩═╗║
#─────────────╔═╝║
#─────────────╚══╝
# By: FUNnectoR
# Tg: @ImCoder12

# Путь к fernflower
fernflower_path: ""
# Тема интерфейса: "dark" или "light"
theme: "dark"
# Имя файла для логирования
log_file: "jar_tool.log"
language: "lang_ru.yml"
# Путь к установленному JDK. Оставьте пустым для автоматического выбора.
jdk_path: ""
# Версия JDK для установки
jdk_version: "17"
# Текущая версия программы
current_version: "1.0.0"